<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<title><?php echo $quiz->name; ?></title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
		
		<link rel="stylesheet" href="css/reset.css" />
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="css/quiz.css" />
	</head>
	
	<body>
		
		<header id="main">
			<h1><?php echo $quiz->name; ?></h1>
			<p><?php echo $quiz->description; ?></p>
		</header>
		
		<div id="container">
		
		<section>
			<form action="index.php" method="post" accept-charset="utf-8">
				
				<?php foreach($quiz->questions as $questionkey => $question): ?>
				
					<fieldset>
					
						<h2><?php echo $question->description; ?></h2>
						
						<ul>
							
						<?php foreach($question->answers as $answerkey => $answer): ?>
							
								<li><label><input type="radio" name="answers[<?php echo $questionkey; ?>]" value="<?php echo $answerkey; ?>"><?php echo $answer->description; ?></label></li>
							
							
						<?php endforeach ?>
						
						</ul>
					</fieldset>
				
				<?php endforeach; ?>
			
				<p><input type="submit" value="submit"></p>
			</form>
		</section>
		
		</div>
		
	</body>

</html>